RES_NET_ARP_ALL changes and QA infra.
lxc/libresource pull request #25
Opened 2023-08-02 23:13 UTC by anjalidk

2023-08-14 17:09 UTC, hallyn requested changes

2023-08-14 17:09 UTC, hallyn commented on Makefile
> +CFLAGS = -g -Wall -Werror -fPIC -std=gnu99 -DTESTING
Do you actually want -DTESTING unconditionally enabled in 'make' ?  or was this meant to stay in a testing branch?

2023-08-14 17:09 UTC, hallyn commented on tests/ARP/arp.sh
> +cat arp_info1.orig | sed 's/? //g' > arp_info.orig
Hm - you really can't count on 'sed -i' being available?

2023-08-14 18:30 UTC, hallyn commented
> I can add a note to README saying sed needs to be installed if testing mode needs to be enabled?

No, I'm saying you appear to be doing
```
cat file1 | sed 's/.../' > file2; mv file2 file1
```
instead of just
```
sed -i 's/.../' file1
```

2023-08-16 02:04 UTC, anjalidk commented
> On Aug 14, 2023, at 11:31 AM, Serge Hallyn ***@***.***> wrote:
> 
> 
> I can add a note to README saying sed needs to be installed if testing mode needs to be enabled?
> 
> No, I'm saying you appear to be doing
> 
> cat file1 | sed 's/.../' > file2; mv file2 file1
> 
> instead of just
> 
> sed -i 's/.../' file1

Yes, thanks done. Pushed with review comments amended to previous commit.

Anjali

> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.
>

2023-08-16 02:07 UTC, hallyn commented on net_arp.c
> +				return -1;
You left the 'return -1' above the 'ret = -1; goto out;'

2023-08-16 02:09 UTC, anjalidk commented
> On Aug 15, 2023, at 7:07 PM, Serge Hallyn ***@***.***> wrote:
> 
> 
> @hallyn commented on this pull request.
> 
> In net_arp.c:
> 
> > +#ifdef PRINTLOGS
> +			printf("r->nlmsg_type is %d (RTM_NEWNEIGH = 28)\n", r->nlmsg_type);
> +			printf("Received ndmsg, len %d\n", len);
> +			printf("ifindex is %d\n", nd_msg->ndm_ifindex);
> +			printf("family: %u\n", nd_msg->ndm_family);
> +			printf("ndm_type: %u\n", nd_msg->ndm_type);
> +			printf("ndm_flags: %u\n",nd_msg->ndm_flags);
> +			printf("ndm_state: %u\n", nd_msg->ndm_state);
> +#endif
> +			len -= NLMSG_LENGTH(sizeof(*nd_msg));
> +			if (len < 0) {
> +				eprintf("nlmsg_len incorrect");
> +				errno = EINVAL;
> +				free(buf);
> +				free(arps);
> +				return -1;
> 
> You left the 'return -1' above the 'ret = -1; goto out;’
> 
Sorry! Committed with return -1 removed.

Anjali

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.
>

2023-08-16 02:28 UTC, hallyn commented on net_arp.c
> +	fp = fopen ("./arp_info.txt", "w");
Now, this is just testing code, so probably no big deal, but you're not checking fopen return value

2023-08-16 02:29 UTC, hallyn commented on net_arp.c
> +	fp = fopen ("./arp_info.txt", "w");
If you're around and push a fix in the next 5m, great - else i'll just merge it as is for now.

2023-08-16 02:38 UTC, anjalidk commented
> On Aug 15, 2023, at 7:29 PM, Serge Hallyn ***@***.***> wrote:
> 
> 
> @hallyn commented on this pull request.
> 
> In net_arp.c:
> 
> > +
> +static int handle_arp_resp(int net_sock, void **out)
> +{
> +	int err, recvl, len, max_arp, arp_size, ret = 0;
> +	int aind = 0, total_arp_size = 0;
> +	struct iovec iov;
> +	struct msghdr msg;
> +	struct nlmsghdr *r;
> +	struct nlmsgerr *nlmsg_err;
> +	struct ndmsg *nd_msg;
> +	struct rtattr *at[NDA_MAX + 1], *rta;
> +	struct arp_info *arps = NULL, *iarps = NULL;
> +	struct sockaddr_nl nladdr;
> +#ifdef TESTING
> +	FILE *fp = NULL;
> +	fp = fopen ("./arp_info.txt", "w");
> 
> If you're around and push a fix in the next 5m, great - else i'll just merge it as is for now.
> 
Yup, I will push shortly..

Anjali

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.
>

2023-08-16 02:41 UTC, anjalidk commented
> On Aug 15, 2023, at 7:37 PM, Anjali Kulkarni ***@***.***> wrote:
> 
> 
> 
>> On Aug 15, 2023, at 7:29 PM, Serge Hallyn ***@***.***> wrote:
>> 
>> 
>> @hallyn commented on this pull request.
>> 
>> In net_arp.c:
>> 
>>> +
>> +static int handle_arp_resp(int net_sock, void **out)
>> +{
>> +	int err, recvl, len, max_arp, arp_size, ret = 0;
>> +	int aind = 0, total_arp_size = 0;
>> +	struct iovec iov;
>> +	struct msghdr msg;
>> +	struct nlmsghdr *r;
>> +	struct nlmsgerr *nlmsg_err;
>> +	struct ndmsg *nd_msg;
>> +	struct rtattr *at[NDA_MAX + 1], *rta;
>> +	struct arp_info *arps = NULL, *iarps = NULL;
>> +	struct sockaddr_nl nladdr;
>> +#ifdef TESTING
>> +	FILE *fp = NULL;
>> +	fp = fopen ("./arp_info.txt", "w");
>> 
>> If you're around and push a fix in the next 5m, great - else i'll just merge it as is for now.
>> 
> Yup, I will push shortly..

Push is done.
Anjali

> 
> Anjali
> 
>> —
>> Reply to this email directly, view it on GitHub, or unsubscribe.
>> You are receiving this because you authored the thread.

2023-08-16 02:43 UTC, hallyn approved these changes

2023-08-16 02:43 UTC, merged